// Generated by gencpp from file l5_robots/CaGrid.msg
// DO NOT EDIT!


#ifndef L5_ROBOTS_MESSAGE_CAGRID_H
#define L5_ROBOTS_MESSAGE_CAGRID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <l5_robots/CaRow.h>

namespace l5_robots
{
template <class ContainerAllocator>
struct CaGrid_
{
  typedef CaGrid_<ContainerAllocator> Type;

  CaGrid_()
    : grid()  {
    }
  CaGrid_(const ContainerAllocator& _alloc)
    : grid(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::l5_robots::CaRow_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::l5_robots::CaRow_<ContainerAllocator> >::other >  _grid_type;
  _grid_type grid;




  typedef boost::shared_ptr< ::l5_robots::CaGrid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::l5_robots::CaGrid_<ContainerAllocator> const> ConstPtr;

}; // struct CaGrid_

typedef ::l5_robots::CaGrid_<std::allocator<void> > CaGrid;

typedef boost::shared_ptr< ::l5_robots::CaGrid > CaGridPtr;
typedef boost::shared_ptr< ::l5_robots::CaGrid const> CaGridConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::l5_robots::CaGrid_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::l5_robots::CaGrid_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace l5_robots

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'l5_robots': ['/home/alex/catkin_ws/src/l5_robots/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::l5_robots::CaGrid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::l5_robots::CaGrid_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::l5_robots::CaGrid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::l5_robots::CaGrid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::l5_robots::CaGrid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::l5_robots::CaGrid_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::l5_robots::CaGrid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0741c1f4072196731466d956358fcef";
  }

  static const char* value(const ::l5_robots::CaGrid_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0741c1f40721967ULL;
  static const uint64_t static_value2 = 0x31466d956358fcefULL;
};

template<class ContainerAllocator>
struct DataType< ::l5_robots::CaGrid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "l5_robots/CaGrid";
  }

  static const char* value(const ::l5_robots::CaGrid_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::l5_robots::CaGrid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "CaRow[] grid\n\
================================================================================\n\
MSG: l5_robots/CaRow\n\
int32[] row\n\
";
  }

  static const char* value(const ::l5_robots::CaGrid_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::l5_robots::CaGrid_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CaGrid_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::l5_robots::CaGrid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::l5_robots::CaGrid_<ContainerAllocator>& v)
  {
    s << indent << "grid[]" << std::endl;
    for (size_t i = 0; i < v.grid.size(); ++i)
    {
      s << indent << "  grid[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::l5_robots::CaRow_<ContainerAllocator> >::stream(s, indent + "    ", v.grid[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // L5_ROBOTS_MESSAGE_CAGRID_H
