// Generated by gencpp from file l5_robots/CaRow.msg
// DO NOT EDIT!


#ifndef L5_ROBOTS_MESSAGE_CAROW_H
#define L5_ROBOTS_MESSAGE_CAROW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace l5_robots
{
template <class ContainerAllocator>
struct CaRow_
{
  typedef CaRow_<ContainerAllocator> Type;

  CaRow_()
    : row()  {
    }
  CaRow_(const ContainerAllocator& _alloc)
    : row(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _row_type;
  _row_type row;




  typedef boost::shared_ptr< ::l5_robots::CaRow_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::l5_robots::CaRow_<ContainerAllocator> const> ConstPtr;

}; // struct CaRow_

typedef ::l5_robots::CaRow_<std::allocator<void> > CaRow;

typedef boost::shared_ptr< ::l5_robots::CaRow > CaRowPtr;
typedef boost::shared_ptr< ::l5_robots::CaRow const> CaRowConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::l5_robots::CaRow_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::l5_robots::CaRow_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace l5_robots

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'l5_robots': ['/home/alex/catkin_ws/src/l5_robots/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::l5_robots::CaRow_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::l5_robots::CaRow_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::l5_robots::CaRow_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::l5_robots::CaRow_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::l5_robots::CaRow_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::l5_robots::CaRow_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::l5_robots::CaRow_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b20dc667218469d78f38ccd9c9712d6";
  }

  static const char* value(const ::l5_robots::CaRow_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b20dc667218469dULL;
  static const uint64_t static_value2 = 0x78f38ccd9c9712d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::l5_robots::CaRow_<ContainerAllocator> >
{
  static const char* value()
  {
    return "l5_robots/CaRow";
  }

  static const char* value(const ::l5_robots::CaRow_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::l5_robots::CaRow_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] row\n\
";
  }

  static const char* value(const ::l5_robots::CaRow_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::l5_robots::CaRow_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.row);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CaRow_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::l5_robots::CaRow_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::l5_robots::CaRow_<ContainerAllocator>& v)
  {
    s << indent << "row[]" << std::endl;
    for (size_t i = 0; i < v.row.size(); ++i)
    {
      s << indent << "  row[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.row[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // L5_ROBOTS_MESSAGE_CAROW_H
